# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=8000']
    -   id: check-ast
    -   id: check-json
    -   id: name-tests-test
        args: ['--django']
-   repo: https://gitlab.com/pycqa/flake8
    rev: a4aeb2e209c64efcfadb43cb96809c1f5b80912b
    hooks:
    -   id: flake8